apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gpu-telemetry-queue.fullname" . }}
  labels:
    {{- include "gpu-telemetry-queue.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "gpu-telemetry-queue.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gpu-telemetry-queue.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: queue
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          env:
            - name: QUEUE_LISTEN_ADDR
              value: {{ .Values.env.QUEUE_LISTEN_ADDR | quote }}
          ports:
            - name: grpc
              containerPort: 50051
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
