apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gpu-telemetry-streamer-data
  namespace: gpu-telemetry
  labels:
    app.kubernetes.io/part-of: gpu-telemetry-pipeline
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
